k8s_version: "1.32"
pod_network_cidr: "10.244.0.0/16"
flannel_manifest: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
kubeconfig_local_path: "~/.kube/config"
domain: "rudolphmaier.de"
subdomain: "node02"
