---
- name: K8s prerequisites
  hosts: k8s_control_plane
  become: true
  roles:
    - k8s-common

- name: K8s control plane bootstrap
  hosts: k8s_control_plane
  become: true
  roles:
    - k8s-control-plane

- name: Install Cilium CNI
  hosts: k8s_control_plane
  become: true
  roles:
    - cilium

- name: Bootstrap ArgoCD
  hosts: k8s_control_plane
  become: true
  roles:
    - argocd-bootstrap
